# Generated by Django 4.1 on 2023-12-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='last_contact',
            field=models.DateField(blank=True, null=True),
        ),
    ]
