# Generated by Django 4.1 on 2023-12-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_job_last_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Very Bad'), (1, 'Bad'), (2, 'Okay'), (3, 'Good'), (4, 'Very Good'), (5, 'Unknown')], default=5),
        ),
    ]
