# Generated by Django 4.1 on 2023-12-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_job_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='priority',
            field=models.IntegerField(choices=[(-2, 'Rejected'), (-1, 'Unknown'), (0, 'Very Bad'), (1, 'Bad'), (2, 'Okay'), (3, 'Good'), (4, 'Very Good')], default=-1),
        ),
    ]
