# Generated by Django 4.1 on 2023-12-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_job_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='priority',
            field=models.IntegerField(choices=[(5, 'Rejected'), (6, 'Unknown'), (10, 'Very Bad'), (15, 'Bad'), (20, 'Okay'), (25, 'Good'), (30, 'Very Good')], default=6),
        ),
    ]
