# Generated by Django 4.1 on 2023-12-13 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_job_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='priority',
            new_name='feeling',
        ),
    ]
