# Generated by Django 4.1 on 2024-02-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_job_feeling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='feeling',
            field=models.IntegerField(choices=[(5, 'Rejected'), (6, 'Unknown'), (10, 'Very Bad'), (15, 'Bad'), (20, 'Okay'), (25, 'Good'), (27, 'Good, but suspended due to other offer'), (30, 'Very Good'), (100, 'Offer')], default=6),
        ),
    ]
